name: flights
version: 1.0.0
profile: flights
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  flights:
    intermediate:
      flights:
        +meta:
          owner: "dbt_project_yml@gmail.com"
          year_created: 2026
seeds:
  dbt_course:
    schema: seeds